binaries:
    SD: './scripts/ext/stringdecomposer/run_decomposer.py'
common:
    threads: 4
mapping:
    max_n_overlaps: 5000
idb:
    mink: 100
    maxk: 300
sd_report_parsing:
    min_ident_diff: 0.015
scaffolding:
    min_connections: 1
path_db:
    k: 600
polishing:
    n_iter: 4
    min_cov: 3
    max_nloc: 1
